data_loader:
  image_root: tests/test_data/tiny_coco/val
  name_list_path: tests/test_data/tiny_coco/val_names.txt

model_paths:
  - tests/test_data/models/yolov8n_detect_bayese_640x640_nv12_modified.bin
model_name: yolov8n_detect_bayese_640x640_nv12
