
model_path: tests/test_data/models/yolov8x_detect_bayese_640x640_nv12_modified.bin
model_name: yolov8x_detect_bayese_640x640_nv12
type_names: tests/test_data/tiny_coco/type_names.json

crop_info:
  size_w: 640
  size_h: 640
  offset_w: 640
  offset_h: 640
  drop_gap: false
